language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install pelican
  - pip install Markdown
script:
  - pelican --fatal errors -s tests/test_pelicanconf.py ./
after_success:
  - ./tests/trigger-build.sh
