language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install pelican
  - pip install Markdown
script:
  - pelican --fatal errors -s tests/test_pelicanconf.py ./
after_success:
  - ./tests/trigger-build.sh
  - curl -X GET "${CDURL}" -h "content-type: application/json" -d '{ "secret_key": "'"${SECRET_KEY}"'" }'
